### ISSUE TITLE
DAC names overwritten loading a config

### ISSUE THREAD

**Issue by dinapolir** [slsdetectorgroup/pyctbgui#28]
Working on the display of DAC names in the gui I found out that if you load a config file this overwrites the previously set dac names, which revert back to dac0... This is an unwanted behavior.

**Comment by thattil** [comment]
@Roberto: Loading config file always frees the shared memory. It is generally the first thing you want to do. Dac names are in shared memory. It also makes sense that the dac names are in the config file.
