### ISSUE TITLE
Behavior of DACs tab

### ISSUE THREAD

**Issue by dinapolir** [slsdetectorgroup/pyctbgui#45]
##### Priority:
High
##### *Describe the bug
The behavior of the mV checkbox in the DACs tab is that it sets the DAC value written in the spinbox. This is potentially risky for the chip (sorry Dhanya, I thought about that only now that I an testing it). The suggested behavior is that the label showing the measured value should display the present value in mV and the actual DAC value should not be modified. If you want to set the dac you have to go in the spin box and press enter.
->Potential risky behavior of tristate described in "Dacs in tristate" issue.

**Comment by thattil** [comment]
So the mV checkbox should only change the label display to mV value? And the dac value written to the dacs via the spinbox is only in dac units?

**Comment by thattil** [comment]
- unchecking/checking mV will only update the label value.
- pressing enter only sends spinbox value to the dac (depending on mv checkbox)
