### ISSUE TITLE
DACs-PSs values not updated 

### ISSUE THREAD

**Issue by dinapolir** [slsdetectorgroup/pyctbgui#5]
DAC values are not updated if they are changed somewhere else (e.g. with a put).
Same thin if you change from mV to DAC units.
I am not sure which is the best approach to fix this. The old gui was just updating everything when switching tab. This generates problems if you switch tab while acquiring. Maybe a button "update" would be the best option.

**Comment by dinapolir** [comment]
The same issue is applying for power supplies; updating all slow ADCs (sense+temperature) at once would also be useful

**Comment by thattil** [comment]
Working on solution that opening each tab fixes the values for that tab.
