### ISSUE TITLE
digital plotting

### ISSUE THREAD

**Issue by dinapolir** [slsdetectorgroup/pyctbgui#79]
##### Priority
Low

Waveforms in the digital plot should be steps between 0 and 1.
Waveforms should not be overlapped on the same graph, but should be plotted in stripes (maybe having a checkbox to select "overlayed" or "stripped" would be optimal).
It should be possible to hide adcs or signals to give more space to the other plot

**Comment by thattil** [comment]
#88 already does hiding the other plot if its not enabled.
