### ISSUE TITLE
problems with waveforms update

### ISSUE THREAD

**Issue by dinapolir** [slsdetectorgroup/pyctbgui#85]
##### Priority:
High
##### *Describe the bug
If you change the dblist/plot checkboxes in the corresponding window, the waveforms do not get updated in the plot (ALSO if you run the pattern again).

**Comment by thattil** [comment]
It plots only when you click on start and does not depend on whether you loaded the pattern again.
All you have to do is check the checkbox for db list or plot and then click on start button to acquire.  This seems to work for me. Is this not the expected functionality?
